### ISSUE TITLE
how to Transform header and footer

### ISSUE THREAD

**Issue by abin103** [OfficeDev/Open-Xml-PowerTools#97] opened 2016-11-09 03:58 UTC
How to Transform the word's header, footer into HTML pages, there is no such code, thank you

**Comment by Will-Gregg** [comment] 2017-02-16 18:02
Duplicate of #95

**Comment by tomjebo** [comment] 2019-02-01 22:53
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.

**Closed by tomjebo** 2019-02-01 22:53 UTC
