### ISSUE TITLE
Table/Document format gets changed after accept all changes using OpenXml Power Tools 4.1.3

### ISSUE THREAD

**Issue by koolprasad2003** [OfficeDev/Open-Xml-PowerTools#57] opened 2016-01-19 06:05 UTC
Hello Team

I am using OpenXml Power Tools 4.1.3 for accepting revision in document, when I use acceptRevision () method from OpenXml Power Tools my document/table gets disturbed and shows contents in single column, if I accept Revisions using Word's 'Accept all changes' menu, document not get  disturbed, it's seems its a BUG of  OpenXml Power Tools 4.1.3. 

I have attached sample document to replicate the issue. see below link

http://1drv.ms/1PloF8g

Please help me out to resolve this problem.

Thanks
Prasad

**Comment by EricWhiteDev** [comment] 2016-01-19 12:37
Hi Prasad,

I see the difference, but am not clear on what is causing this.  It seems as though the issue is not one of putting the content into a single column, but of causing some change in the displayed width of the columns of tables.  The displayed width of columns is fairly complex to control, in that Word is allowed to override widths, taking them more as suggested widths, in order to layout the table to look as good as possible.

I am currently buried in the project of making the next version of the Open XML SDK, so difficult to schedule this right now.

One way that you could really help me is to create the simplest document that demonstrates the bug.  I will be able to attend to this bug sooner if I have a document that is as simple as possible, and accepting revisions shows the issue.  I don't think that this is a serious issue, and if I have a simple repro, then can solve it quickly.

Cheers, Eric

**Comment by koolprasad2003** [comment] 2016-02-03 12:48
I will be very grateful to you if you fix it in upcoming version of OpenXMLPowerTool. As this is not a big issue but due to document looks disturbed, users get confused and simply marked it as 'Disturbed', Please he me to fix it.

**Comment by tomjebo** [comment] 2019-02-01 22:58
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.

**Closed by tomjebo** 2019-02-01 22:58 UTC
